Contact.destroy_all

# 100.times do
#   contact1 = Contact.new(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number)
#   contact1.save
#   p contact1
# end

Contact.create!([
  {first_name: "Majora", last_name: "Carter", email: "majora@email.com", phone_number: "3424331111", middle_name: nil, bio: nil},
  {first_name: "Danilo", last_name: "Campos", email: "danilo@email.com", phone_number: "5424331111", middle_name: nil, bio: nil},
  {first_name: "bill", last_name: "bob", email: "bill@bob.com", phone_number: "23456789", middle_name: nil, bio: nil},
  {first_name: "Easton", last_name: "Gutkowski", email: "garrick_schulist@schulist.biz", phone_number: "622-865-2515", middle_name: nil, bio: nil},
  {first_name: "Earlene", last_name: "Nolan", email: "marquise@bartell.co", phone_number: "1-236-151-8001 x2228", middle_name: nil, bio: nil},
  {first_name: "Monique", last_name: "Bogan", email: "dusty.brakus@beahanledner.net", phone_number: "(924) 459-5067 x70572", middle_name: nil, bio: nil},
  {first_name: "Katrina", last_name: "Champlin", email: "maxime.jacobi@kertzmann.biz", phone_number: "1-382-396-2978", middle_name: nil, bio: nil},
  {first_name: "Layla", last_name: "Mertz", email: "roxane@sporer.biz", phone_number: "(522) 049-5668 x2890", middle_name: nil, bio: nil},
  {first_name: "Zula", last_name: "Wehner", email: "jedidiah.padberg@hackett.com", phone_number: "901-176-7114 x60830", middle_name: nil, bio: nil},
  {first_name: "Barbara", last_name: "Grady", email: "shayna@kunze.com", phone_number: "865-472-0681 x850", middle_name: nil, bio: nil},
  {first_name: "Patrick", last_name: "Hilll", email: "vance_johnston@douglaskaulke.biz", phone_number: "316.940.5018 x2480", middle_name: nil, bio: nil},
  {first_name: "Tyrel", last_name: "Wilderman", email: "santos@andersonsteuber.org", phone_number: "1-515-754-2780", middle_name: nil, bio: nil},
  {first_name: "Elda", last_name: "Mann", email: "ayla_orn@murphy.name", phone_number: "(422) 342-2653", middle_name: nil, bio: nil},
  {first_name: "Durward", last_name: "Kertzmann", email: "lydia@king.info", phone_number: "107-785-4108 x7246", middle_name: nil, bio: nil},
  {first_name: "Curt", last_name: "Cummings", email: "eve.casper@metz.io", phone_number: "(268) 700-7297 x463", middle_name: nil, bio: nil},
  {first_name: "Judy", last_name: "Beahan", email: "ubaldo.steuber@reilly.co", phone_number: "572.011.1940 x4773", middle_name: nil, bio: nil},
  {first_name: "Efren", last_name: "Graham", email: "mathilde@buckridgebrekke.info", phone_number: "1-602-246-6599 x3603", middle_name: nil, bio: nil},
  {first_name: "Jalon", last_name: "McGlynn", email: "rashawn@langworth.com", phone_number: "428.509.9680 x869", middle_name: nil, bio: nil},
  {first_name: "Imani", last_name: "Smith", email: "buddy@bergstrom.io", phone_number: "1-255-650-4448", middle_name: nil, bio: nil},
  {first_name: "Juston", last_name: "Kunze", email: "henri@ziemebailey.name", phone_number: "532-259-9315", middle_name: nil, bio: nil},
  {first_name: "Rey", last_name: "Torp", email: "luella_bailey@batz.info", phone_number: "873.491.2387", middle_name: nil, bio: nil},
  {first_name: "Alvah", last_name: "Heidenreich", email: "francisca@prohaska.name", phone_number: "483.357.9251", middle_name: nil, bio: nil},
  {first_name: "Titus", last_name: "Block", email: "caie@kiehnheathcote.net", phone_number: "1-209-849-3079", middle_name: nil, bio: nil},
  {first_name: "Frederick", last_name: "Strosin", email: "hortense@keler.net", phone_number: "1-264-801-8967 x894", middle_name: nil, bio: nil},
  {first_name: "Isai", last_name: "Lubowitz", email: "darien_little@wuckert.com", phone_number: "944.074.6329 x305", middle_name: nil, bio: nil},
  {first_name: "Kareem", last_name: "Hilll", email: "blair@rutherford.org", phone_number: "(684) 072-3517", middle_name: nil, bio: nil},
  {first_name: "Alexandra", last_name: "Farrell", email: "elza.gutkowski@schamberger.name", phone_number: "1-761-427-9240 x5984", middle_name: nil, bio: nil},
  {first_name: "Olaf", last_name: "Brown", email: "dejon.romaguera@torpabbott.io", phone_number: "371-902-0966 x94540", middle_name: nil, bio: nil},
  {first_name: "Kaley", last_name: "Berge", email: "dangelo.skiles@schmittoconnell.org", phone_number: "560-949-4531 x75563", middle_name: nil, bio: nil},
  {first_name: "Adriana", last_name: "Carter", email: "jordane.deckow@bergemante.biz", phone_number: "(207) 218-7445", middle_name: nil, bio: nil},
  {first_name: "Amber", last_name: "Kutch", email: "rory@willms.biz", phone_number: "766.465.5320 x37704", middle_name: nil, bio: nil},
  {first_name: "Desiree", last_name: "Hickle", email: "marilie.jerde@bahringer.io", phone_number: "1-416-609-5436", middle_name: nil, bio: nil},
  {first_name: "Dorian", last_name: "Hintz", email: "santa.huels@altenwerthlangworth.io", phone_number: "763-502-0715", middle_name: nil, bio: nil},
  {first_name: "Cordell", last_name: "Collins", email: "dariana_quitzon@lockman.io", phone_number: "116-258-8324", middle_name: nil, bio: nil},
  {first_name: "Shakira", last_name: "Schneider", email: "joey@steuber.biz", phone_number: "888.781.9161 x782", middle_name: nil, bio: nil},
  {first_name: "Lorine", last_name: "Schaden", email: "hal@gutkowskikunde.co", phone_number: "1-367-330-1449 x7736", middle_name: nil, bio: nil},
  {first_name: "Regan", last_name: "Brekke", email: "christine@oconnellwaters.name", phone_number: "698.136.6273", middle_name: nil, bio: nil},
  {first_name: "Dan", last_name: "Corwin", email: "stan.jacobs@wizabogisich.com", phone_number: "1-206-484-9237 x4680", middle_name: nil, bio: nil},
  {first_name: "Christy", last_name: "Buckridge", email: "jodie@pagacmcglynn.net", phone_number: "471.691.3133 x7720", middle_name: nil, bio: nil},
  {first_name: "Luz", last_name: "Leannon", email: "kaleb@larkin.co", phone_number: "(613) 180-5008 x156", middle_name: nil, bio: nil},
  {first_name: "Peyton", last_name: "Hilpert", email: "antonette.torphy@roberts.co", phone_number: "1-443-604-6210 x0111", middle_name: nil, bio: nil},
  {first_name: "Annamae", last_name: "Leannon", email: "guie@leffler.org", phone_number: "496.285.3982 x240", middle_name: nil, bio: nil},
  {first_name: "Justus", last_name: "Schultz", email: "dolly_murazik@heaneyoberbrunner.org", phone_number: "1-291-812-4604 x1622", middle_name: nil, bio: nil},
  {first_name: "Yoshiko", last_name: "Bogisich", email: "pearline_reynolds@stiedemannmueller.name", phone_number: "101-286-0827 x343", middle_name: nil, bio: nil},
  {first_name: "Katherine", last_name: "Lynch", email: "kayleigh@schulist.info", phone_number: "822-632-5431 x6694", middle_name: nil, bio: nil},
  {first_name: "Ozella", last_name: "Kemmer", email: "bart_gleason@hane.net", phone_number: "1-496-553-3841 x05569", middle_name: nil, bio: nil},
  {first_name: "Nathen", last_name: "Hammes", email: "destiny_kreiger@green.name", phone_number: "(638) 897-1243 x5854", middle_name: nil, bio: nil},
  {first_name: "Dortha", last_name: "Oberbrunner", email: "dayton.larson@crist.net", phone_number: "1-286-640-1484 x02944", middle_name: nil, bio: nil},
  {first_name: "Pearline", last_name: "Koelpin", email: "rosalee@andersonlarson.io", phone_number: "561.893.1680", middle_name: nil, bio: nil},
  {first_name: "Avery", last_name: "Dietrich", email: "pink_cormier@terryoreilly.biz", phone_number: "380-229-3933 x9152", middle_name: nil, bio: nil},
  {first_name: "Osbaldo", last_name: "Becker", email: "jonathan@trantow.com", phone_number: "752-701-7124 x0198", middle_name: nil, bio: nil},
  {first_name: "Kamron", last_name: "Gutmann", email: "anastasia@quigley.net", phone_number: "481-773-7304", middle_name: nil, bio: nil},
  {first_name: "Adrain", last_name: "Nader", email: "milan@blanda.name", phone_number: "585.396.4637", middle_name: nil, bio: nil},
  {first_name: "Pearline", last_name: "Murphy", email: "ralph_bogisich@osinskibotsford.net", phone_number: "260-062-1948 x4974", middle_name: nil, bio: nil},
  {first_name: "Travon", last_name: "Konopelski", email: "terrell@romaguera.biz", phone_number: "(722) 783-7004 x3283", middle_name: nil, bio: nil},
  {first_name: "Noemi", last_name: "Maggio", email: "sophie_borer@oberbrunner.info", phone_number: "(634) 929-6988 x4781", middle_name: nil, bio: nil},
  {first_name: "Cindy", last_name: "Toy", email: "lois@cole.co", phone_number: "952-025-7012 x21878", middle_name: nil, bio: nil},
  {first_name: "Brooks", last_name: "Lemke", email: "hulda.mccullough@schamberger.net", phone_number: "363.072.2247 x711", middle_name: nil, bio: nil},
  {first_name: "Reina", last_name: "Boyer", email: "santina_kris@heller.org", phone_number: "1-942-455-0385 x7644", middle_name: nil, bio: nil},
  {first_name: "Trent", last_name: "Hand", email: "haleigh@schamberger.net", phone_number: "1-100-896-7355 x005", middle_name: nil, bio: nil},
  {first_name: "Kailey", last_name: "Lubowitz", email: "rosanna.bauch@harvey.info", phone_number: "142.426.7204 x054", middle_name: nil, bio: nil},
  {first_name: "Arno", last_name: "Orn", email: "brady@lindgren.co", phone_number: "(446) 439-7355", middle_name: nil, bio: nil},
  {first_name: "Daniela", last_name: "Brown", email: "hank@jast.org", phone_number: "273-818-2200", middle_name: nil, bio: nil},
  {first_name: "Gage", last_name: "Hirthe", email: "kayden.jaskolski@aufderhar.name", phone_number: "(280) 710-0265 x0436", middle_name: nil, bio: nil},
  {first_name: "Elise", last_name: "Windler", email: "percy@eichmann.name", phone_number: "956-512-9314", middle_name: nil, bio: nil},
  {first_name: "Noemy", last_name: "Glover", email: "erich@skiles.net", phone_number: "847-182-1426 x3813", middle_name: nil, bio: nil},
  {first_name: "Gregoria", last_name: "Lubowitz", email: "oma_murphy@boyer.info", phone_number: "1-482-317-6211 x25467", middle_name: nil, bio: nil},
  {first_name: "Nikko", last_name: "Friesen", email: "tyshawn@keleranderson.io", phone_number: "269.404.2881", middle_name: nil, bio: nil},
  {first_name: "Filomena", last_name: "Ankunding", email: "charity@crooks.info", phone_number: "890.102.4725 x30294", middle_name: nil, bio: nil},
  {first_name: "Enoch", last_name: "Paucek", email: "estel_johnston@grimeslynch.biz", phone_number: "652-776-1292", middle_name: nil, bio: nil},
  {first_name: "Sydnee", last_name: "Smith", email: "robert_bogan@jacobsonbednar.org", phone_number: "1-605-113-7048 x012", middle_name: nil, bio: nil},
  {first_name: "Joe", last_name: "Jan", email: "joe@jan.com", phone_number: "345678", middle_name: "seph", bio: "newbio"},
  {first_name: "Jermey", last_name: "Sipes", email: "kamren.tremblay@connelly.biz", phone_number: "904.926.2334 x52002", middle_name: nil, bio: nil},
  {first_name: "Keyon", last_name: "Harber", email: "gwen.ruecker@grahamweber.io", phone_number: "707.592.5176 x058", middle_name: nil, bio: nil},
  {first_name: "Tyrell", last_name: "Greenholt", email: "misael@lubowitzrenner.io", phone_number: "795-874-4365", middle_name: nil, bio: nil},
  {first_name: "Aurelia", last_name: "Gibson", email: "susie_thompson@rippinframi.info", phone_number: "1-461-543-2331", middle_name: nil, bio: nil},
  {first_name: "Timmothy", last_name: "Dickinson", email: "tad@gutkowskikertzmann.biz", phone_number: "(567) 293-9731 x3624", middle_name: nil, bio: nil},
  {first_name: "Petra", last_name: "Kiehn", email: "cary_balistreri@connromaguera.biz", phone_number: "1-900-891-8466 x82515", middle_name: nil, bio: nil},
  {first_name: "Citlalli", last_name: "Balistreri", email: "rahul.tillman@damorekozey.co", phone_number: "(224) 544-5971 x262", middle_name: nil, bio: nil},
  {first_name: "Golden", last_name: "Durgan", email: "wendy_volkman@bauch.biz", phone_number: "1-128-375-2213 x54211", middle_name: nil, bio: nil},
  {first_name: "Brook", last_name: "Grant", email: "dallin_goodwin@connelly.io", phone_number: "396.288.9445", middle_name: nil, bio: nil},
  {first_name: "Reinhold", last_name: "Runte", email: "cali@glover.info", phone_number: "963.312.1647 x3660", middle_name: nil, bio: nil},
  {first_name: "Brad", last_name: "Becker", email: "noble@collier.io", phone_number: "850-064-7313", middle_name: nil, bio: nil},
  {first_name: "Aisha", last_name: "McDermott", email: "florence_orn@gusikowskimoriette.info", phone_number: "380-515-2562 x60863", middle_name: nil, bio: nil},
  {first_name: "Marianna", last_name: "Johnson", email: "damaris_howe@hansenernser.info", phone_number: "1-586-740-0198", middle_name: nil, bio: nil},
  {first_name: "Koby", last_name: "Streich", email: "danny_mccullough@romaguera.co", phone_number: "959-387-6967", middle_name: nil, bio: nil},
  {first_name: "Fabian", last_name: "Wehner", email: "jody.blanda@walter.biz", phone_number: "202-054-8780", middle_name: nil, bio: nil},
  {first_name: "Bethany", last_name: "Roberts", email: "chelsie@jacobson.com", phone_number: "217.411.8963 x6701", middle_name: nil, bio: nil},
  {first_name: "Matilda", last_name: "O'Hara", email: "nathanial_schamberger@windler.net", phone_number: "949.530.2211 x7260", middle_name: nil, bio: nil},
  {first_name: "Hipolito", last_name: "Swaniawski", email: "rosemary@hagenes.org", phone_number: "963-189-4175", middle_name: nil, bio: nil},
  {first_name: "Lesly", last_name: "Gerhold", email: "laury@mitchellreinger.info", phone_number: "1-877-149-8754", middle_name: nil, bio: nil},
  {first_name: "Christop", last_name: "Stoltenberg", email: "phoebe.gutmann@lefflersanford.io", phone_number: "468.439.5861 x03470", middle_name: nil, bio: nil},
  {first_name: "Osborne", last_name: "Price", email: "morton.yost@heel.io", phone_number: "1-524-842-1306 x958", middle_name: nil, bio: nil},
  {first_name: "Emilio", last_name: "Willms", email: "tommie_king@wilkinson.org", phone_number: "371.542.8250", middle_name: nil, bio: nil},
  {first_name: "Myles", last_name: "Mills", email: "sammy_willms@white.net", phone_number: "1-244-787-3223 x910", middle_name: nil, bio: nil},
  {first_name: "Winnifred", last_name: "Sipes", email: "reece@prohaska.net", phone_number: "(296) 624-8332 x511", middle_name: nil, bio: nil},
  {first_name: "Merle", last_name: "Schaden", email: "valentina_corkery@bergnaum.co", phone_number: "(628) 889-8928 x94394", middle_name: nil, bio: nil},
  {first_name: "Talia", last_name: "Walter", email: "hershel@dubuque.org", phone_number: "(303) 593-2923", middle_name: nil, bio: nil},
  {first_name: "Jensen", last_name: "Stoltenberg", email: "caria.heathcote@prosacco.biz", phone_number: "331-085-0672 x648", middle_name: nil, bio: nil},
  {first_name: "Alexandrea", last_name: "Wolf", email: "rasheed.parisian@prosaccomckenzie.net", phone_number: "1-515-111-2620 x68576", middle_name: nil, bio: nil},
  {first_name: "Omer", last_name: "Dickinson", email: "kaden.mayer@hackettoconner.name", phone_number: "(222) 892-2619 x75811", middle_name: nil, bio: nil},
  {first_name: "Karen", last_name: "Bahringer", email: "jaclyn_terry@hoppeboyle.org", phone_number: "644.541.5307 x01781", middle_name: nil, bio: nil},
  {first_name: "Marco", last_name: "Bashirian", email: "philip.predovic@raynorjerde.net", phone_number: "286.637.9945 x8451", middle_name: nil, bio: nil},
  {first_name: "Otilia", last_name: "Bogan", email: "percival.koch@smith.net", phone_number: "(432) 283-0963 x7752", middle_name: nil, bio: nil},
  {first_name: "John", last_name: "asdkjfhasdf", email: nil, phone_number: nil, middle_name: nil, bio: nil},
  {first_name: "Saron", last_name: "Yitbarek", email: "edit@email.com", phone_number: "3424331111", middle_name: nil, bio: "here is a thing but i want it to have more than 255  characters so that I can prove that it is not a string and it is in fact a text attribute saved in the database as;dlkfjalsk;dfj;alsdfjlk;asdjflk;asdjfkl;asdjfkl;asdjfkl;asjdfl;kasdjfkl;asdjflkasdjfkl;asdjfl;kasdjflkasdjfldsakfjasdl;kfj"},
  {first_name: "ilknur", last_name: "cho", email: nil, phone_number: nil, middle_name: nil, bio: nil},
  {first_name: "raul", last_name: "dan", email: "some_sor_of_email", phone_number: "34567890", middle_name: "serino", bio: ";alksdfjl;kasdjfasdfj"}
])
p "I'm done! everything worked!"
